/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElButton: (typeof import('element-plus/es'))['ElButton']
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
        ElMessage: (typeof import('element-plus/es'))['ElMessage']
        ElResult: (typeof import('element-plus/es'))['ElResult']
        ElRow: (typeof import('element-plus/es'))['ElRow']
        Header: (typeof import('./src/components/layout/Header.vue'))['default']
        HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
        Layout: (typeof import('./src/components/layout/index.vue'))['default']
        RouterLink: (typeof import('vue-router'))['RouterLink']
        RouterView: (typeof import('vue-router'))['RouterView']
    }
}
