/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        Aside: (typeof import('./src/components/layout/aside.vue'))['default']
        ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
        ElButton: (typeof import('element-plus/es'))['ElButton']
        ElMenu: (typeof import('element-plus/es'))['ElMenu']
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
        ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
        ElPageHeader: (typeof import('element-plus/es'))['ElPageHeader']
        ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
        Header: (typeof import('./src/components/layout/Header.vue'))['default']
        HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
        Layout: (typeof import('./src/components/layout/index.vue'))['default']
        RouterLink: (typeof import('vue-router'))['RouterLink']
        RouterView: (typeof import('vue-router'))['RouterView']
    }
}
